// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClkWF8HbaR7duPP7YGr_Eqiirc4bvHFew',
    appId: '1:577538902384:web:ab6566c9a368fe9fd327b5',
    messagingSenderId: '577538902384',
    projectId: 'khoon-app',
    authDomain: 'khoon-app.firebaseapp.com',
    storageBucket: 'khoon-app.firebasestorage.app',
    measurementId: 'G-Y3K7KXYFPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQeSC2hDDtO8a4FoVCuI3VkdLxmVnnL6k',
    appId: '1:577538902384:android:2e436d996044e2ddd327b5',
    messagingSenderId: '577538902384',
    projectId: 'khoon-app',
    storageBucket: 'khoon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FgEzpncoo3aABmvj3bk-mIQCPb5IAlE',
    appId: '1:577538902384:ios:9c541d6d3d33c1e8d327b5',
    messagingSenderId: '577538902384',
    projectId: 'khoon-app',
    storageBucket: 'khoon-app.firebasestorage.app',
    iosBundleId: 'com.rayansattarkhan.khoonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClkWF8HbaR7duPP7YGr_Eqiirc4bvHFew',
    appId: '1:577538902384:web:a68ac04735bfdf71d327b5',
    messagingSenderId: '577538902384',
    projectId: 'khoon-app',
    authDomain: 'khoon-app.firebaseapp.com',
    storageBucket: 'khoon-app.firebasestorage.app',
    measurementId: 'G-PVXDLRL41K',
  );
}
